version: '3'

services:
  backend:
    image: docker.judan.dev/wine-backend
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/dev
      - JWT_SECRET=${JWT_SECRET}
  frontend:
    image: docker.judan.dev/wine-frontend
    ports:
      - 80:80
    restart: unless-stopped
  db:
    image: postgres:16
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=dev

