version: "3"

services:
  vscode:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye
    volumes:
      - ./:/workspaces/wine-tracker:cached
    command: sleep infinity
  db:
    image: postgres:16
    restart: unless-stopped
    ports:
      - 5432:5432